### ISSUE TITLE
MaxSize should be in kilobytes.

### ISSUE THREAD

**Issue by anasanzari** [natefinch/lumberjack#84] opened 2019-04-11 14:29 UTC

**Comment by natefinch** [comment] 2019-04-11 14:36
This is a duplicate of #37 - the size should really be in bytes, so you can specify whatever size you want. Making it megabytes was a mistake.  I probably will add a new field that is bytes, and maybe a constructor that takes bytes, and deprecate using the struct directly.

**Closed as completed** 2019-04-11 14:40 UTC
Labels: duplicate
