### ISSUE TITLE
version 2 on github does not match examples

### ISSUE THREAD

**Issue by tvmaly** [natefinch/lumberjack#15] opened 2015-10-18 14:29 UTC
It appears that when I try to pass a Filename as in the example using the v2 branch on github, it does not work.  I checked the code and the Filename is not present in the v2 branch of github.

```
log.SetOutput(&lumberjack.Logger{
    Filename: "somefile",
    MaxSize:  10,
})
```

**Comment by natefinch** [comment] 2015-10-28 02:01
Not sure what the problem is, but the field is there: https://github.com/natefinch/lumberjack/blob/v2.0/lumberjack.go#L72

**Comment by natefinch** [comment] 2016-02-18 18:24
Did you ever figure this out?

**Comment by natefinch** [comment] 2016-02-26 15:18
Closing this for now. Let me know if you still are having problems.

**Closed as completed by natefinch** 2016-02-26 15:18 UTC
